### ISSUE TITLE
selecting multiple categories by holding control

### ISSUE THREAD

**Issue by orchards92** [bimone/addins-colorsplasher#2]
I'm trying to select multiple categories by holding control like shown in the app but it doesn't seam to work for me.  I have tried reinstalling the newest version and I'm using Revit 2020.

Has anyone else had this issue?

**Comment by h-pl** [comment]
I have the same problem. And the developer said,  [This is a known bug of the latest version and we are planning on getting it fixed.](https://apps.autodesk.com/RVT/en/Detail/Index?id=5056644120649615847&appLang=en&os=Win64)

**Comment by jmcouffin** [comment]
@h-pl you were right, at the time.
we did not have the time and workforce to look into it, that is why we decided to make it open source and leave it in the hands of the community to fix it.

**Comment by jmcouffin** [comment]
@orchards92 @h-pl 
fixed by https://github.com/bimone/addins-colorsplasher/commit/a1aff5221ede7ac51a5f3019621369841ed4f729
