### ISSUE TITLE
Need this for 2022!

### ISSUE THREAD

**Issue by anitopi11x** [bimone/addins-colorsplasher#4]
Could really use this in 2022 totally forgot before updating files...

**Comment by DuncanLithgow** [comment]
Would be great with some tips on what we'll need to make this work in 2022. @jmcouffin @AlainBolduc are you some of the original devs?

**Comment by jmcouffin** [comment]
The steps are as follow: 
1. clone repo
2. open solution in visual studio 
3. edit the properties of the solution to change the post build events to 
![image](https://user-images.githubusercontent.com/7872003/161565929-b8ddeb0d-8769-4973-8bab-366e3ece9756.png)
4. build the solution

**Comment by jmcouffin** [comment]
[ColorSplasher.zip](https://github.com/bimone/addins-colorsplasher/files/8410530/ColorSplasher.zip)
you can also copy the content of this zip file to %appdata%\Autodesk\Revit\Addins\2022\

**Comment by DuncanLithgow** [comment]
@jmcouffin please keep this issue open. It has not been resolved until the codebase works for 2022. I will look into how to do what you mention, hopefully in the easter break. You can assign this to me if you want.

**Comment by arunvinayak** [comment]
I still cant find how to use this in Revit 2022

**Comment by DuncanLithgow** [comment]
@arunvinayak Have you tried copying the contents of the zip file as earlier suggested?

**Comment by Fozibehr** [comment]
@jmcouffin Is it possible to get the same changes made for 2022 for 2023?

**Comment by Hecheva** [comment]
If I try to clone the solution I get this error on Visual Studio:
"Index was outside the bounds of the array"
And then I can't see the project

**Comment by jmcouffin** [comment]
> "Index was outside the bounds of the array"

I tried to clone the repo, and haven't had any issue @Hecheva

**Comment by jmcouffin** [comment]
> @jmcouffin Is it possible to get the same changes made for 2022 for 2023?

@Fozibehr It is possible. It does require a certain amount of work as the api for units is quite different, some sections of the code require a rework.

**Comment by Fozibehr** [comment]
It sounds typical of version changes. Thanks for the input.

**Comment by Fozibehr** [comment]
As an alternative program, users can use OneFilter by DiRoots. It's a free utility found on the Autodesk App Store and works up to Revit v23 (on hopefully beyond). 

![Image 001](https://user-images.githubusercontent.com/59780562/190131928-3c08a557-7e65-4db1-8d3b-60dee2463ab2.jpg)

**Comment by talisman** [comment]
> . It does require a certain amount of work as the api for units is quite different, some sections of the code require a rework.

I was able to get it to work with a minor change , see issue #6  .

**Comment by jmcouffin** [comment]
@Fozibehr 
2023 version available thanks to @talisman
