### ISSUE TITLE
"Color Splasher" for Revit 2014

### ISSUE THREAD

**Issue by atpo007** [bimone/addins-colorsplasher#5]
Where can I find and download the "Color Splasher" add-on for Revit 2014?

**Comment by DuncanLithgow** [comment]
probably not going to happen

**Comment by jmcouffin** [comment]
> Where can I find and download the "Color Splasher" add-on for Revit 2014?

especially when autodesk does not support or allow the use of more than 4 years back backward Revit version
you could try build it and see. But I have no idea if the code compatible with Revit 2014 api is still there @atpo007
