### ISSUE TITLE
Make it compile for Revit 2023

### ISSUE THREAD

**Issue by talisman** [bimone/addins-colorsplasher#6]
I have tried to compile for Revit 2023 and there was just one issue which I was able to resolve. 
For Revit 2022 it gave me  a deprecation warning but did compile.
It has to do with the transition from **ParameterType** to **SpecTypeId** , I changed line  580 in _Views/ColorSplasherWindow.xaml.cs_
instead of this 

`                    if (ParameterType.YesNo == p.Definition.ParameterType) {
`
this  
`                    if (SpecTypeId.Boolean.YesNo == p.Definition.GetDataType()) {
`
I don't know if or how to join the project and commit, also - how would someone go about checking whether the version is 2022 or up .
Kind regards , Jonathan Talisman

**Comment by jmcouffin** [comment]
Thanks for that
you can copy the atteached file in %appdata%\Autodesk\Revit\Addins\2023
[ColorSplasher2023.zip](https://github.com/bimone/addins-colorsplasher/files/10040334/ColorSplasher2023.zip)

**Comment by jmcouffin** [comment]
@talisman 
in order to 'join' the project, you just have to fork the project, then you can send your PRs to the source repo.

**Comment by talisman** [comment]
thanks , will try to do so next time.
