### ISSUE TITLE
Link for Revit 2022 not valid

### ISSUE THREAD

**Issue by Mic-94** [bimone/addins-colorsplasher#9]
Link for Revit 2022 is not valid:
[https://github.com/floriangouy/addins-colorsplasher/releases/download/v23.0.0.0/ColorSplasher2022.zip](url)

Could you update link?

**Comment by octavio-nila-teecom** [comment]
Same here. Having issues finding the ColorSplasher.dll file

**Comment by jmcouffin** [comment]
https://github.com/floriangouy/addins-colorsplasher/releases/tag/v22.0.0.0

Here it is.
